#route:
#  group_by: ["alertname", "instance"]
#  group_wait: 10s
#  group_interval: 10s
#  repeat_interval: 3h
#  receiver: "webhook"
#
#receivers:
#  - name: "webhook"
#    webhook_configs:
#      - url: "https://localhost:9099/alert"

global:
  resolve_timeout: 5m
  http_config:
    tls_config:
      insecure_skip_verify: true
    follow_redirects: true
    enable_http2: true
    proxy_url: null

route:
  receiver: webhook
  group_by:
    - alertname
    - instance
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 3h

receivers:
  - name: webhook
    webhook_configs:
      - send_resolved: true
        http_config:
          tls_config:
            insecure_skip_verify: true
          follow_redirects: true
          enable_http2: true
          proxy_url: null
        url: "https://monitooring.it.hariduskeskus.ee:9099/alert"