route:
  group_by: ["alertname", "instance"]
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 2h
  receiver: "webhook"

receivers:
  - name: "webhook"
    webhook_configs:
      - url: "http://localhost:9099/alert"