global:
  scrape_interval: 15s

scrape_configs:

  - job_name: 'linux_exporter'
    scrape_interval: 15s
    static_configs:
      - targets: ['10.10.50.6:9100','10.10.60.4:9100']

  - job_name: 'windows_exporter'
    scrape_interval: 15s
    static_configs:
      - targets: ['10.10.50.5:9182', '10.10.60.3:9182']

  - job_name: '302_workstations'
    dns_sd_configs:
      - names:
        - '*.32.10.10.in-addr.arpa'
        refresh_interval: 10s
        type: 'A'
        port: 9182

  - job_name: '303_workstations'
    dns_sd_configs:
      - names:
        - '*.33.10.10.in-addr.arpa'
        refresh_interval: 10s
        type: 'A'
        port: 9182

  - job_name: '304_workstations'
    dns_sd_configs:
      - names:
        - '*.34.10.10.in-addr.arpa'
        refresh_interval: 10s
        type: 'A'
        port: 9182

  - job_name: '308_workstations'
    dns_sd_configs:
      - names:
        - '*.38.10.10.in-addr.arpa'
        refresh_interval: 10s
        type: 'A'
        port: 9182

  - job_name: 'switch_exporter' # switchi placeholder
    scrape_interval: 15s
    static_configs:
      - targets: ['10.10.50.2:9100']

  - job_name: 'router_exporter' # ruuteri placeholder
    scrape_interval: 15s
    static_configs:
      - targets: ['10.10.50.1:9100']

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - 'localhost:9093'

rule_files:
  - 'alerts.yml'
