global:
  scrape_interval: 1m

scrape_configs:
  - job_name: "linux_servers"
    scrape_interval: 1m
    scheme: https
    tls_config:
      ca_file: /etc/prometheus/ca.crt
      insecure_skip_verify: true
    basic_auth:
      username: prometheus
      password: Prometheus
    static_configs:
      - targets: ["10.10.50.4:9100"]
        labels:
          type: "Server"
          instance: "FOG"
      - targets: ["10.10.60.2:9100"]
        labels:
          type: "Server"
          instance: "Proxmox"
      - targets: ["10.10.50.222:9100"]
        labels:
          type: "Server"
          instance: "Prometheus"
      - targets: ["10.10.60.4:9100"]
        labels:
          type: "Server"
          instance: "VPN"

  - job_name: "windows_servers"
    scrape_interval: 1m
    scheme: https
    tls_config:
      ca_file: /etc/prometheus/ca.crt
      insecure_skip_verify: true
    basic_auth:
      username: prometheus
      password: Prometheus
    static_configs:
      - targets: ["10.10.60.3:9182"]
        labels:
          type: "Server"
          instance: "DC2"
      - targets: ["10.10.50.5:9182"]
        labels:
          type: "Server"
          instance: "DC1"

  - job_name: "302_workstations"
    file_sd_configs:
      - files:
          - "/etc/prometheus/scrape_configs/302.json"
        refresh_interval: 12h
    relabel_configs:
      - source_labels: [__address__]
        regex: "^(.*)$"
        replacement: "${1}:9182"
        target_label: __address__
    scrape_interval: 5m

  - job_name: "303_workstations"
    file_sd_configs:
      - files:
          - "/etc/prometheus/scrape_configs/303.json"
        refresh_interval: 12h
    relabel_configs:
      - source_labels: [__address__]
        regex: "^(.*)$"
        replacement: "${1}:9182"
        target_label: __address__
    scrape_interval: 5m

  - job_name: "304_workstations"
    file_sd_configs:
      - files:
          - "/etc/prometheus/scrape_configs/304.json"
        refresh_interval: 12h
    relabel_configs:
      - source_labels: [__address__]
        regex: "^(.*)$"
        replacement: "${1}:9182"
        target_label: __address__
    scrape_interval: 5m

  - job_name: "308_workstations"
    file_sd_configs:
      - files:
          - "/etc/prometheus/scrape_configs/308.json"
        refresh_interval: 12h
    relabel_configs:
      - source_labels: [__address__]
        regex: "^(.*)$"
        replacement: "${1}:9182"
        target_label: __address__
    scrape_interval: 5m

  - job_name: "switch"
    scrape_interval: 1m
    scheme: https
    tls_config:
      ca_file: /etc/prometheus/ca.crt
      insecure_skip_verify: true
    basic_auth:
      username: prometheus
      password: Prometheus
    static_configs:
      - targets: ["127.0.0.1:9116"]
        labels:
          type: "Võrguseade"
          __param_target: "10.10.50.2"
          instance: "Switch"
    metrics_path: "/snmp"
    params:
      module: [planet_switch]
    relabel_configs:
      - target_label: __address__
        replacement: "127.0.0.1:9116"

  - job_name: "truenas"
    scrape_interval: 1m
    scheme: https
    tls_config:
      ca_file: /etc/prometheus/ca.crt
      insecure_skip_verify: true
    basic_auth:
      username: prometheus
      password: Prometheus
    static_configs:
      - targets: ["127.0.0.1:9117"]
        labels:
          type: "Server"
          __param_target: "10.10.50.6"
          instance: "TrueNAS"
    metrics_path: "/snmp"
    params:
      module: [truenas]
    relabel_configs:
      - target_label: __address__
        replacement: "127.0.0.1:9117"

  - job_name: "router"
    scrape_interval: 1m
    scheme: https
    tls_config:
      ca_file: /etc/prometheus/ca.crt
      insecure_skip_verify: true
    basic_auth:
      username: prometheus
      password: Prometheus
    static_configs:
      - targets: ["172.0.0.1:49091"]
        labels:
          type: "Võrguseade"
          __param_target: "10.10.50.1"
          instance: "Router"
    relabel_configs:
      - target_label: __address__
        replacement: "127.0.0.1:49091"

  - job_name: "openvpn"
    scrape_interval: 1m
#    scheme: https
#    tls_config:
#      ca_file: /etc/prometheus/prometheus.crt
#      insecure_skip_verify: true
#    basic_auth:
#      username: prometheus
#      password: Prometheus
    static_configs:
      - targets: ["10.10.60.4:50011"]
        labels:
          type: "VPN"
          instance: "VPN"

alerting:
  alertmanagers:
    - static_configs:
        - targets: ["monitooring.it.hariduskeskus.ee:9093"]
      scheme: https
      tls_config:
        insecure_skip_verify: true
      basic_auth:
        username: prometheus
        password: Prometheus
#          tls_config:
#            cert_file: /etc/prometheus/prometheus.crt
#            key_file: /etc/prometheus/prometheus.key

rule_files:
  - "alerts.yml"
