global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'linux_exporter' # linuxi masinad
    scrape_interval: 15s
    static_configs:
      - targets: ['192.168.1.4:9100','192.168.1.5:9100']
  - job_name: 'windows_exporter' # windowsi serverid ja töömasinad
    scrape_interval: 15s
    static_configs:
      - targets: ['192.168.1.2:9182','192.168.1.3:9182']
  - job_name: 'snmp_exporter' # switchi placeholder
    scrape_interval: 15s
    static_configs:
      - targets: ['192.168.1.1:9100']

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - 'localhost:9093'

rule_files:
  - 'alerts.yml'
