{
 "title": "Klassid",
 "tags": [
  "Windows",
  "Klass",
  "302",
  "303",
  "304",
  "308"
 ],
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "30m",
 "templating": {
  "list": [
   {
    "name": "pcnames",
    "query": {
     "query": "label_values(windows_logical_disk_free_bytes{job=\"308_workstations\"},instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "A302 C:/",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1 - (windows_logical_disk_free_bytes{job=\"302_workstations\", volume=\"C:\"}/windows_logical_disk_size_bytes{job=\"302_workstations\", volume=\"C:\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "A303 C:/",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1 - (windows_logical_disk_free_bytes{job=\"303_workstations\", volume=\"C:\"}/windows_logical_disk_size_bytes{job=\"303_workstations\", volume=\"C:\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "A304 C:/",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1 - (windows_logical_disk_free_bytes{job=\"304_workstations\", volume=\"C:\"}/windows_logical_disk_size_bytes{job=\"304_workstations\", volume=\"C:\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "A308 C:/",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1 - (windows_logical_disk_free_bytes{job=\"308_workstations\", volume=\"C:\"}/windows_logical_disk_size_bytes{job=\"308_workstations\", volume=\"C:\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}