{
 "title": "Linux Serverid [Detailne]",
 "description": "Node Exporter (Linux) dashboard",
 "tags": [
  "Linux",
  "Serverid"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "job",
    "query": {
     "query": "label_values(node_uname_info{job=~\"linux_servers\"},job)"
    }
   },
   {
    "name": "server",
    "label": "Server",
    "query": {
     "query": "label_values(node_uname_info{job=~\"$job\"},instance)"
    }
   },
   {
    "name": "device",
    "label": "NIC",
    "query": {
     "query": "label_values(node_network_info{instance=~\"$server\", device!~\"'tap.*|veth.*|br.*|docker.*|virbr.*|lo.*|cni.*'\"},device)"
    }
   },
   {
    "name": "maxmount",
    "label": "最大挂载目录",
    "query": {
     "query": "query_result(topk(1,sort_desc (max(node_filesystem_size_bytes{instance=~'$server',fstype=~\"ext.?|xfs\",mountpoint!~\".*pods.*\"}) by (mountpoint))))"
    }
   },
   {
    "name": "show_hostname",
    "label": "Display hostname",
    "query": {
     "query": "label_values(node_uname_info{job=~\"$job\", instance=~\"$server\"},nodename)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(time() - node_boot_time_seconds{instance=~\"$server\"})"
    }
   ]
  },
  {
   "title": "CPU cores",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(node_cpu_seconds_total{instance=~\"$server\", mode='system'})"
    }
   ]
  },
  {
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{instance=~\"$server\",mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "CPU usage"
    },
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{instance=~\"$server\"} / (node_memory_MemTotal_bytes{instance=~\"$server\"})))* 100",
     "legendFormat": "RAM usage"
    },
    {
     "expr": "(1 - ((node_memory_SwapFree_bytes{instance=~\"$server\"} + 1)/ (node_memory_SwapTotal_bytes{instance=~\"$server\"} + 1))) * 100",
     "legendFormat": "Swap usage"
    }
   ]
  },
  {
   "title": "Traffic per hour $device",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "increase(node_network_receive_bytes_total{instance=~\"$server\",device=~\"$device\"}[60m])",
     "legendFormat": "{{device}} download"
    },
    {
     "expr": "increase(node_network_transmit_bytes_total{instance=~\"$server\",device=~\"$device\"}[60m])",
     "legendFormat": "{{device}} upload"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{instance=\"$server\"}",
     "legendFormat": "UP"
    }
   ]
  },
  {
   "title": "Total RAM",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes{instance=~\"$server\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU iowait",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(irate(node_cpu_seconds_total{instance=~\"$server\",mode=\"iowait\"}[5m])) * 100"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg(irate(node_cpu_seconds_total{instance=~\"$server\",mode=\"system\"}[5m])) by (instance) *100",
     "legendFormat": "System usage"
    },
    {
     "expr": "avg(irate(node_cpu_seconds_total{instance=~\"$server\",mode=\"user\"}[5m])) by (instance) *100",
     "legendFormat": "User usage"
    },
    {
     "expr": "avg(irate(node_cpu_seconds_total{instance=~\"$server\",mode=\"iowait\"}[5m])) by (instance) *100",
     "legendFormat": "Disk IO usage"
    },
    {
     "expr": "(1 - avg(irate(node_cpu_seconds_total{instance=~\"$server\",mode=\"idle\"}[5m])) by (instance))*100",
     "legendFormat": "Total usage"
    }
   ]
  },
  {
   "title": "RAM information",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$server\"}",
     "legendFormat": "Total"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$server\"} - node_memory_MemAvailable_bytes{instance=~\"$server\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "node_memory_MemAvailable_bytes{instance=~\"$server\"}",
     "legendFormat": "Available"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$server\"} - (node_memory_Cached_bytes{instance=~\"$server\"} - node_memory_Buffers_bytes{instance=~\"$server\"} - node_memory_MemFree_bytes{instance=~\"$server\"})",
     "legendFormat": "{{instance}}_used (total-cache-buf-free)"
    },
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{instance=~\"$server\"} / (node_memory_MemTotal_bytes{instance=~\"$server\"})))* 100",
     "legendFormat": "Usage rate"
    }
   ]
  },
  {
   "title": "Bandwidth usage per second $device",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{instance=~'$server',device=~\"$device\"}[5m])*8",
     "legendFormat": "{{device}} download"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{instance=~'$server',device=~\"$device\"}[5m])*8",
     "legendFormat": "{{device}} upload"
    }
   ]
  },
  {
   "title": "System load average",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_load1{instance=~\"$server\"}",
     "legendFormat": "1 minute load"
    },
    {
     "expr": "node_load5{instance=~\"$server\"}",
     "legendFormat": "5 minute load"
    },
    {
     "expr": "node_load15{instance=~\"$server\"}",
     "legendFormat": "15 minute load"
    }
   ]
  },
  {
   "title": "Disk read and write capacity per second",
   "type": "timeseries",
   "description": "Read bytes The number of bits read per second per disk partition\nWritten bytes The number of bits written per second per disk partition.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "irate(node_disk_read_bytes_total{instance=~\"$server\"}[5m])",
     "legendFormat": "{{device}} read"
    },
    {
     "expr": "irate(node_disk_written_bytes_total{instance=~\"$server\"}[5m])",
     "legendFormat": "{{device}} write"
    }
   ]
  },
  {
   "title": "Disk usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(node_filesystem_size_bytes{instance=~'$server',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}-node_filesystem_free_bytes{instance=~'$server',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}) *100/(node_filesystem_avail_bytes {instance=~'$server',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}+(node_filesystem_size_bytes{instance=~'$server',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}-node_filesystem_free_bytes{instance=~'$server',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}))",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "Disk read and write rate (IOPS)",
   "type": "timeseries",
   "description": "Reads completed: The number of read completions per disk partition per second\n\nWrites completed: Number of write completions per disk partition per second\n\nIO now The number of input/output requests being processed per disk partition per second",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "irate(node_disk_reads_completed_total{instance=~\"$server\"}[5m])",
     "legendFormat": "{{device}} read"
    },
    {
     "expr": "irate(node_disk_writes_completed_total{instance=~\"$server\"}[5m])",
     "legendFormat": "{{device}} write"
    }
   ]
  },
  {
   "title": "Proportion of I/O operation time per second",
   "type": "timeseries",
   "description": "The time spent on I/O in every second of natural time. (wall-clock time)\n\nnode_disk_io_time_seconds_total:\nThe number of seconds the disk spent on input/output operations. This value is cumulative. (Milliseconds Spent Doing I/Os)\n\nirate(node_disk_io_time_seconds_total[1m])：\nCalculate the rate per second: (last value - last previous value) / timestamp difference, that is: the proportion of time the disk spends on I/O operations within 1 second.",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "irate(node_disk_io_time_seconds_total{instance=~\"$server\"}[5m])",
     "legendFormat": "{{device}} I/O ops per second%"
    }
   ]
  },
  {
   "title": "Time consumption of each IO read and write (reference: less than 100ms)",
   "type": "timeseries",
   "description": "Read time seconds The number of seconds spent on each disk partition read operation\n\nWrite time seconds The number of seconds spent writing each disk partition.\n\nIO time seconds The number of seconds spent on input/output operations per disk partition\n\nIO time weighted seconds Weighted seconds spent on input/output operations per disk partition",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "irate(node_disk_read_time_seconds_total{instance=~\"$server\"}[5m]) / irate(node_disk_reads_completed_total{instance=~\"$server\"}[5m])",
     "legendFormat": "{{device}} read"
    },
    {
     "expr": "irate(node_disk_write_time_seconds_total{instance=~\"$server\"}[5m]) / irate(node_disk_writes_completed_total{instance=~\"$server\"}[5m])",
     "legendFormat": "{{device}} write"
    }
   ]
  },
  {
   "title": "Network Socket connection information",
   "type": "timeseries",
   "description": "Sockets_used - Total number of sockets used across all protocols\n\nCurrEstab - Number of TCP connections currently in ESTABLISHED or CLOSE-WAIT state\n\nTCP_alloc - the number of allocated (established, sk_buff applied for) TCP sockets\n\nTCP_tw - Number of TCP connections waiting to be closed\n\nUDP_inuse - Number of UDP sockets in use\n\nRetransSegs - Number of TCP retransmission messages\n\nOutSegs - Number of packets sent by TCP\n\nInSegs - Number of packets received by TCP",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_netstat_Tcp_CurrEstab{instance=~'$server'}",
     "legendFormat": "CurrEstab"
    },
    {
     "expr": "node_sockstat_TCP_tw{instance=~'$server'}",
     "legendFormat": "TCP_tw"
    },
    {
     "expr": "node_sockstat_sockets_used{instance=~'$server'}",
     "legendFormat": "Sockets_used"
    },
    {
     "expr": "node_sockstat_UDP_inuse{instance=~'$server'}",
     "legendFormat": "UDP_inuse"
    },
    {
     "expr": "node_sockstat_TCP_alloc{instance=~'$server'}",
     "legendFormat": "TCP_alloc"
    },
    {
     "expr": "irate(node_netstat_Tcp_InSegs{instance=~'$server'}[5m])",
     "legendFormat": "Tcp_InSegs"
    },
    {
     "expr": "irate(node_netstat_Tcp_OutSegs{instance=~'$server'}[5m])",
     "legendFormat": "Tcp_OutSegs"
    },
    {
     "expr": "irate(node_netstat_Tcp_RetransSegs{instance=~'$server'}[5m])",
     "legendFormat": "Tcp_RetransSegs"
    }
   ]
  },
  {
   "title": "Open file descriptors (left) / number of context switches per second (right)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_filefd_allocated{instance=~\"$server\"}",
     "legendFormat": "File descriptor used"
    },
    {
     "expr": "irate(node_context_switches_total{instance=~\"$server\"}[5m])",
     "legendFormat": "Context switches per second"
    }
   ]
  },
  {
   "title": "Total file descriptors",
   "type": "stat",
   "gridPos": { "h": 2, "w": 8, "x": 8, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(node_filefd_maximum{instance=~\"$server\"})"
    }
   ]
  }
 ]
}