{
 "title": "OpenVPN Server",
 "description": "Simple OpenVPN Metrics dashboard for Prometheus openvpn_exporter",
 "tags": [
  "VPN",
  "Serverid"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": {
     "query": "label_values(openvpn_build_info{instance=\"VPN\"},instance)"
    }
   },
   {
    "name": "interval",
    "label": "Time period",
    "query": "5m,10m,15m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "At a glance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "type": "stat",
   "description": "Whether scraping OpenVPN's metrics was successful.",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{instance=~\"$instance\",type=\"VPN\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Connected Clients",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(openvpn_connected_since{instance=\"$instance\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Time since last status update",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "clocks" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - abs(openvpn_last_updated{instance=~\"$instance\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total bytes sent",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(openvpn_bytes_sent{instance=\"$instance\"}[1d]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total bytes received",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(openvpn_bytes_received{instance=\"$instance\"}[1d]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top Traffic",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10, sum(increase(openvpn_bytes_received{instance=\"$instance\", common_name!=\"UNDEF\"}[1d])+increase(openvpn_bytes_sent{instance=\"$instance\", common_name!=\"UNDEF\"}[1d]))by(common_name))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "General",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {}
   ]
  },
  {
   "title": "OpenVPN Exporter Status",
   "type": "timeseries",
   "description": "Whether scraping OpenVPN's metrics was successful.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "openvpn_server_info{instance=~\"$instance\", type=\"VPN\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Clients Connected",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (instance) (openvpn_connections{instance=\"$instance\"})",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Bytes Sent",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by (instance) (rate(openvpn_bytes_sent{instance=~\"$instance\"}[$interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Bytes Received",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by (instance) (rate(openvpn_bytes_received{instance=~\"$instance\"}[$interval]))",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Client Activity",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Top 10 Traffic",
   "type": "barchart",
   "description": "Top 10 total traffic by users.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "topk(10, sum(increase(openvpn_bytes_received{instance=\"$instance\",common_name!=\"UNDEF\"}[$interval])+increase(openvpn_bytes_sent{instance=\"$instance\",common_name!=\"UNDEF\"}[$interval]))by(common_name))",
     "legendFormat": "{{ common_name }}"
    }
   ]
  },
  {
   "title": "Top 5 Client Network Activity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "topk(5, sum by (common_name) (increase(openvpn_bytes_received{instance=\"$instance\", common_name!=\"UNDEF\"}[$interval])))",
     "legendFormat": "{{ common_name }} - IN"
    },
    {
     "expr": "topk(5, sum by (common_name) (increase(openvpn_bytes_sent{instance=\"$instance\", common_name!=\"UNDEF\"}[$interval])))",
     "legendFormat": "{{ common_name }} - OUT"
    }
   ]
  },
  {
   "title": "Current OpenVPN Clients",
   "type": "table",
   "gridPos": { "h": 18, "w": 24, "x": 0, "y": 45 },
   "targets": [
    {
     "expr": "sort_desc(\r\n  sum(rate(openvpn_bytes_received{instance=\"$instance\", common_name!=\"UNDEF\"}[$interval])) by (common_name)\r\n)\r\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "sort_desc(\r\n  sum(rate(openvpn_bytes_sent{instance=\"$instance\", common_name!=\"UNDEF\"}[$interval])) by (common_name)\r\n)\r\n"
    },
    {
     "expr": "sum(increase(openvpn_bytes_sent{instance=\"$instance\", common_name!=\"UNDEF\"}[$interval])) by (common_name) +\r\nsum(increase(openvpn_bytes_received{instance=\"$instance\", common_name!=\"UNDEF\"}[$interval])) by (common_name)\r\n"
    }
   ]
  }
 ]
}