{
 "title": "Switch [Detailne]",
 "description": "SNMP EXPORTER",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "Job", "query": { "query": "label_values(ifInOctets,job)" } },
   {
    "name": "instance",
    "query": {
     "query": "label_values(ifInOctets{instance!=\"TrueNAS\"},instance)"
    }
   },
   {
    "name": "Interface",
    "query": {
     "query": "query_result(ifInOctets{instance=\"$instance\",ifDescr!~\"VLAN.*$\"})"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "timeticks" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sysUpTime{instance=\"$instance\",job=\"$Job\"}",
     "legendFormat": "In"
    }
   ]
  },
  {
   "title": "Maximum outflow (current)",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(irate(ifOutOctets{instance=\"$instance\",job=\"$Job\"}[5m]))"
    }
   ]
  },
  {
   "title": "Maximum inflow (current)",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(irate(ifInOctets{instance=\"$instance\",job=\"$Job\"}[5m]))",
     "legendFormat": "In"
    }
   ]
  },
  {
   "title": "Total outflow",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(delta(ifOutOctets{instance=\"$instance\",job=\"$Job\"}[$__range]))",
     "legendFormat": "Out"
    }
   ]
  },
  {
   "title": "Total inflow",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(delta(ifInOctets{instance=\"$instance\",job=\"$Job\"}[$__range]))",
     "legendFormat": "In"
    }
   ]
  },
  {
   "title": "$Interface IN/OUT",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "irate(ifInOctets{job='$Job',ifDescr=~'$Interface',instance='$instance'}[5m])",
     "legendFormat": "IN: {{ifDescr}}"
    },
    {
     "expr": "irate(ifOutOctets{job='$Job',ifDescr=~'$Interface',instance='$instance'}[5m])",
     "legendFormat": "OUT: {{ifDescr}}"
    }
   ]
  },
  {
   "title": "All ports in/out (last 5 minutes)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "rate(ifInOctets{job=\"$Job\"}[5m])",
     "legendFormat": "IN: {{ifDescr}}"
    },
    {
     "expr": "rate(ifOutOctets{job=\"$Job\"}[5m])",
     "legendFormat": "OUT: {{ifDescr}}"
    }
   ]
  },
  {
   "title": "State",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Port status (last 5 minutes)",
   "type": "table-old",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "irate(ifOutOctets{instance=\"$instance\", ifIndex!~\"^([0-9]{1,6})$\", job=\"$Job\"}[5m])",
     "legendFormat": "OUT"
    },
    {
     "expr": "irate(ifInOctets{instance=\"$instance\", ifIndex!~\"^([0-9]{1,6})$\", job=\"$Job\"}[5m])",
     "legendFormat": "IN"
    },
    {
     "expr": "abs(delta(ifOutOctets{instance=\"$instance\", ifIndex!~\"^([0-9]{1,6})$\", job=\"$Job\"}[5m]))",
     "legendFormat": "total out"
    },
    {
     "expr": "abs(delta(ifInOctets{instance=\"$instance\", ifIndex!~\"^([0-9]{1,6})$\", job=\"$Job\"}[5m]))",
     "legendFormat": "total in"
    },
    {
     "expr": "ifHighSpeed{instance=\"$instance\", ifIndex!~\"^([0-9]{1,6})$\", job=\"$Job\"}",
     "legendFormat": "high speed"
    }
   ]
  }
 ]
}