{
 "title": "TrueNAS Server",
 "tags": [
  "NAS",
  "Serverid"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "timeticks" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sysUpTime{instance=\"TrueNAS\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Used RAM",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 9, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "memTotalReal - memAvailReal", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "CPU usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 11, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ssCpuSystem ", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total RAM",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "memTotalReal", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "NET IN/OUT",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    { "expr": "rate(ifHCInOctets[5m])", "legendFormat": "IN: {{ifName}}" },
    { "expr": "rate(ifHCOutOctets[5m])", "legendFormat": "OUT: {{ifName}}" }
   ]
  },
  {
   "title": "Drive Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "targets": [
    {
     "expr": "sum by (instance) (hrStorageUsed)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk I/O R/W Bytes",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "rate(diskIONWrittenX[5m])", "legendFormat": "Write: {{diskIOIndex}}" },
    { "expr": "rate(diskIONReadX[5m])", "legendFormat": "Read: {{diskIOIndex}}" }
   ]
  },
  {
   "title": "SNMP connection statistics",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "snmp_scrape_pdus_returned{instance=\"TrueNAS\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "SNMP connection statistics",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "targets": [
    {
     "expr": "snmp_scrape_packets_sent{instance=\"TrueNAS\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}